### ISSUE TITLE
 Inquiry About Code Availability for "RHINO: Regularizing the Hash-based Implicit Neural Representation"

### ISSUE THREAD

**Issue by Fau1ks** [Ezio77/DINER#8]
Hi, I am currently working on a project related to Implicit Neural Representation. Recently, I came across your remarkable paper titled "RHINO: Regularizing the Hash-based Implicit Neural Representation," and I was truly impressed by the innovative methods you proposed.In particular, I believe that your approach could greatly enhance my current research.
    I am writing to inquire if you have any plans to release the code associated with your paper. Having access to your implementation would be incredibly beneficial for my research and would allow me to build upon your excellent work.
    Best regards.

**Comment by Ezio77** [comment]
I'm sorry but this paper is not my work, you can check this url for code. https://github.com/MELANCHOLY828/RHINO

**Comment by Fau1ks** [comment]
> I'm sorry but this paper is not my work, you can check this url for code. https://github.com/MELANCHOLY828/RHINO

Thank you so much! This is really helpful to me!
